### ISSUE TITLE
Account for special chars in blog name

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost-Desktop#261] opened 2017-03-30 11:32 UTC
In view menu

![image](https://cloud.githubusercontent.com/assets/120485/24502251/47217bf8-154d-11e7-932c-e7f9153c71ec.png)

PS. sorry for having an annoying name

**Comment by mcizol** [comment] 2017-04-12 15:18
I can't reproduce this bug. Is that already fixed? 

<img width="483" alt="screen shot 2017-04-12 at 17 18 02" src="https://cloud.githubusercontent.com/assets/7622781/24965327/02a4b4e8-1fa4-11e7-8d58-e2b68e537219.png">

**Comment by felixrieseberg** [comment] 2017-05-23 19:33
I think it is 🤔  Closing this now

**Closed by felixrieseberg** 2017-05-23 19:33 UTC
Labels: bug
