### ISSUE TITLE
Stuck at waiting to load on Linux 64bit

### ISSUE THREAD

**Issue by primaltutor** [TryGhost/Ghost-Desktop#78] opened 2016-03-28 03:53 UTC
Same issue I saw when on windows originally. Lets me log in but nothing shows, just the spinning I'm doing something icon. I'm using Ubuntu 16.04 (beta2) for this.

Terminal spits out the following.

![screenshot from 2016-03-27 22-49-40](https://cloud.githubusercontent.com/assets/13662679/14070657/acce0f9e-f46e-11e5-9c75-147c90051e93.png)

**Comment by felixrieseberg** [comment] 2016-03-28 05:20
Thanks - seems like I messed up the Linux build. Thanks for letting us know!

Solution: Build correctly, for Linux. In short: Don't break things during build.

**Comment by felixrieseberg** [comment] 2016-03-30 23:50
Assigned to @halfdan!

**Closed** 2016-04-08 18:57 UTC

**Comment by halfdan** [comment] 2016-04-11 08:43
@felixrieseberg Did this get resolved? Back from vacay and got time to check this out if this is still an issue.

**Comment by felixrieseberg** [comment] 2016-04-11 15:20
The root cause is still an issue (the root cause being that I suck at making Linux builds). Basically, what we need is for someone to take the repo, build it, and package it up in a way that makes sense for people who run Ubuntu.

There's a super secret launch date™ - if I send that to you together with the tag that we're targeting, maybe you can run `ember electron:package --platform linux --arch ia32` and ensure that stuff actually works. Ooooor, alternatively, I could try to make a build with my little Ubuntu VM and you tell me if I messed it up ;-)
