### ISSUE TITLE
General Post Image preview

### ISSUE THREAD

**Issue by mece888** [TryGhost/Ghost-Desktop#73] opened 2016-03-25 13:13 UTC
Noticed this problems on OSX (but from the other issues, I guess this is also happening on Win)

1. Existing posts with featured images are not fetching the cover 
<img width="321" alt="screen shot 2016-03-25 at 2 07 41 pm" src="https://cloud.githubusercontent.com/assets/2639560/14044679/8325a760-f293-11e5-9fad-06138dd492a1.png">

2. Adding a feature image doesn't work at all (uploading is never completed).

**Comment by felixrieseberg** [comment] 2016-03-25 18:12
@primaltutor had the same issue - thanks to both of you for reporting. I sadly can't reproduce the issue... could you do me a giant favor and check for the following:

* Hit `Cmd/Ctrl + Alt + Shift + I` to bring up the developer tools for the currently open Ghost blog. Is there anything in the console that you see?
* Is your blog a https or a http blog?
* Are you running on Ghost Pro or self-hosted?

**Comment by felixrieseberg** [comment] 2016-04-08 18:57
This is probably fixed with the mixed content bugfix.

**Closed by felixrieseberg** 2016-04-08 18:57 UTC
