### ISSUE TITLE
Never loads the blog...

### ISSUE THREAD

**Issue by kaiserhase** [TryGhost/Ghost-Desktop#64] opened 2016-03-22 12:33 UTC
After adding the URL, Username, and Pass for my blogs... nothing happens. Just the Ghost circle loading animation, in perpetuity.

**Comment by kaiserhase** [comment] 2016-03-22 12:46
Update: Uninstalled Win 64bit, installe 32bit: Same issue.

**Comment by ceee** [comment] 2016-03-22 14:49
Same here.

Console shows error:
`Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\tobi\AppData\Local\ghost\app-0.1.0\resources\app\node_modules\keytar\build\Release\keytar.node` in `ATOM_SHELL_ASAR.js:140`.

Console for current blog has the output as follows:
![image](https://cloud.githubusercontent.com/assets/445092/13955605/951cd2ea-f045-11e5-9e41-d26581b6fd76.png)

**Comment by ceee** [comment] 2016-03-22 14:51
Possible duplicate of #63

**Comment by felixrieseberg** [comment] 2016-03-22 17:59
Thank you all! I identified an issue with the DLL compilation (we're storing your passwords in the native Windows secure key vault, which is failing here), which lead me to fix an issue in one of our build tools (ember electron).

I'll push out a new version in about two hours, probably sooner. Again, thanks a lot!

(Also closing this as a duplicate of #63)

**Closed by felixrieseberg** 2016-03-22 17:59 UTC
