### ISSUE TITLE
Error opening Koenig Draft post

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost-Desktop#323] opened 2018-07-26 13:25 UTC
We've had a report of an issue with the desktop app when trying to open up the Koenig Draft post that was added with Ghost 1.25.2 on Ghost Desktop app v1.6.0 for Mac

The error displayed is as follows:

```
Failed to compile /Applications/Ghost.app/Contents/Resources/app/main/load-error/error.html: ENOENT: no such file or directory, lstat '/Applications/Ghost.app/Contents/Resources/app/main'
Error: ENOENT: no such file or directory, lstat '/Applications/Ghost.app/Contents/Resources/app/main'
    at Object.realpathSync (fs.js:1669:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at cachedRealpath (/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-compile/lib/sanitize-paths.js:25:22)
    at sanitizeFilePath (/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-compile/lib/sanitize-paths.js:52:16)
    at FileChangedCache.getCacheEntryForPath (/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:201:48)
    at /Applications/Ghost.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:127:41
    at Generator.next (<anonymous>)
    at step (/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:27:191)
    at /Applications/Ghost.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:27:437
    at Promise (<anonymous>)
```

This error seems to present itself a few seconds after loading in the editor. See screenshot below as well:

![error](https://puu.sh/B3qA9/3b81db56c4.png)

Expected behaviour would be that you are able to view/edit the content like a normal story.

**Comment by kevinansfield** [comment] 2018-07-30 16:00
In my testing so far I've only been able to reproduce this with the injected demo post. The post loads and displays fine but then crashes - possibly something to do with the external images or the twitter/youtube embed cards.

The error message that is rendered looks a bit misleading unless it's pointing to something I don't know about how Electron apps work.

**Comment by kevinansfield** [comment] 2018-07-31 15:32
Log when opening a post that crashes when running locally:

```
[16:18:38.745] [info] gh-instance-host: WebView Ghostbusters will navigate: 
[16:18:38.765] [info] gh-instance-host: WebView Ghostbusters encountered load error: undefined
[16:18:38.779] [warn] Ghost Instance failed to load.
[16:18:38.780] [warn] Error Code: undefined, Description: 
[16:18:39.287] [info] gh-instance-host: WebView Ghostbusters did-finish-loading
[16:18:39.288] [info] gh-instance-host: WebView Ghostbusters Not trying to sign in. { isAttemptedSignin: true, title: 'Ghost failed to load' }
```

It seems to be caused by errors thrown by external scripts in embed cards hitting the [_handleLoadFailure](https://github.com/TryGhost/Ghost-Desktop/blob/master/app/components/gh-instance-host.js#L240-L282) method. I commented out the function body and replaced it with a `log.info(e)` call which lets posts load fine. You can see that the Twitter embed was the cause of this particular failure: 

```
{
    currentTarget:
    {
        allowpopups: true,
        autosize: false,
        blinkfeatures: '',
        disableblinkfeatures: '',
        disableguestresize: false,
        disablewebsecurity: true,
        guestinstance: 3,
        httpreferrer: '',
        jQuery33109043267443677721: { events: [Object] },
        maxheight: 0,
        maxwidth: 0,
        minheight: 0,
        minwidth: 0,
        nodeintegration: false,
        partition: '',
        plugins: false,
        preload: 'file:///Users/kevinansfield/code/ghost/Ghost-Desktop/electron-out/project/ember-electron/main/preload.js',
        src: 'http://ghost.blog/ghost/#/editor/5b460e26eca2fe3072efe7e8',
        useragent: '',
        webpreferences: ''
    },
    delegateTarget:
    {
        allowpopups: true,
        autosize: false,
        blinkfeatures: '',
        disableblinkfeatures: '',
        disableguestresize: false,
        disablewebsecurity: true,
        guestinstance: 3,
        httpreferrer: '',
        jQuery33109043267443677721: { events: [Object] },
        maxheight: 0,
        maxwidth: 0,
        minheight: 0,
        minwidth: 0,
        nodeintegration: false,
        partition: '',
        plugins: false,
        preload: 'file:///Users/kevinansfield/code/ghost/Ghost-Desktop/electron-out/project/ember-electron/main/preload.js',
        src: 'http://ghost.blog/ghost/#/editor/5b460e26eca2fe3072efe7e8',
        useragent: '',
        webpreferences: ''
    },
    handleObj:
    {
        guid: 68,
        namespace: '',
        origType: 'did-fail-load',
        type: 'did-fail-load'
    },
    jQuery3310904326744367772: true,
    originalEvent:
    {
        errorCode: -3,
        errorDescription: '',
        isMainFrame: false,
        isTrusted: false,
        validatedURL: 'https://platform.twitter.com/jot.html'
    },
    target:
    {
        allowpopups: true,
        autosize: false,
        blinkfeatures: '',
        disableblinkfeatures: '',
        disableguestresize: false,
        disablewebsecurity: true,
        guestinstance: 3,
        httpreferrer: '',
        jQuery33109043267443677721: { events: [Object] },
        maxheight: 0,
        maxwidth: 0,
        minheight: 0,
        minwidth: 0,
        nodeintegration: false,
        partition: '',
        plugins: false,
        preload: 'file:///Users/kevinansfield/code/ghost/Ghost-Desktop/electron-out/project/ember-electron/main/preload.js',
        src: 'http://ghost.blog/ghost/#/editor/5b460e26eca2fe3072efe7e8',
        useragent: '',
        webpreferences: ''
    },
    timeStamp: 7957.225,
    type: 'did-fail-load'
}
```

@felixrieseberg my Electron knowledge is non-existent so apologies if this is a crazy idea but would it be possible to check `originalEvent.validatedUrl` against the registered blog URL so that we only show an error screen when loading the blog itself fails?

**Comment by felixrieseberg** [comment] 2018-08-08 15:17
@kevinansfield had the correct hunch, we're now only failing if the "main frame" fails to load.

Fixed in https://github.com/TryGhost/Ghost-Desktop/commit/a67d960c4d88f55b37b2f5a8c7d9d9db24f7f61f

**Closed by felixrieseberg** 2018-08-08 15:17 UTC
Labels: bug
