### ISSUE TITLE
0.5.1: Word Count Missing

### ISSUE THREAD

**Issue by flikteoh** [TryGhost/Ghost-Desktop#160] opened 2016-06-13 13:34 UTC
Just noticed Word Count seems to be missing in the Preview page for this version.

It was working on 0.4.0

![screen shot 2016-06-13 at 21 32 35](https://cloud.githubusercontent.com/assets/1472065/16009285/89aeffc8-31ae-11e6-8cf1-aa9c022974be.png)

**Comment by bnookala** [comment] 2016-06-13 22:54
Hi @flikteoh, I'm looking into this bug, and can't reproduce on 0.5.1. Could you let me know what version of Ghost (*not Ghost Desktop), you're running?

Thanks!
Bhargav

**Comment by flikteoh** [comment] 2016-06-14 02:40
Hey @bnookala I'm on Ghost 0.8.0

**Comment by flikteoh** [comment] 2016-06-14 05:51
Hey @bnookala @ErisDS @felixrieseberg 

Regarding to this [editor issue](https://github.com/TryGhost/Ghost-Desktop/issues/159) and the word count problem.

So this HTTP2 Preload Headers thingy suddenly strike my mind this afternoon.

I had it removed on one of my blog (Blog A) and both word counts and the editor is now working magically fine.

While my another blog (Blog B) have exact match of all the setup of Blog A with the Preload Headers in place, the editor is remained as blank screen.

Not sure if both of them are related. But my problems are solved by removing the preload header thingy.

Thanks.

**Comment by bnookala** [comment] 2016-06-14 21:19
@flikteoh Can you elaborate on the HTTP2 Preload Headers? Are you talking about the `preload` link attribute? https://w3c.github.io/preload/#server-push-http-2

**Comment by flikteoh** [comment] 2016-06-15 00:50
Hi @bnookala 

I was actually referring to one of the new feature release on HTTP2 Preload Header for [Ghost 0.8.0](https://dev.ghost.org/ghost-0-8-0/)

I've added `preloadHeaders: 100` into my ghost config file and it stopped the Ghost Desktop editing and word count from working.

Now that I have removed it, everything was back to working normal again.

**Comment by bnookala** [comment] 2016-06-17 18:35
@flikteoh Thanks for your feedback, this will be useful to us, and I'll let the Ghost team know that it appears to be causing issues within the desktop app. For now, I'm closing this issue, since it doesn't appear to be related to Ghost Desktop itself :)

**Closed by bnookala** 2016-06-17 18:35 UTC
