### ISSUE TITLE
Desktop App 1.4 can't log in to blog

### ISSUE THREAD

**Issue by vurtomatic** [TryGhost/Ghost-Desktop#297] opened 2017-11-03 04:18 UTC
1.3 worked fine. 

1.4: No error, just a spinning circle.

Let me know if there's a way to provide a log.

Blog details:
```
Version 1.16.1
Environment production
Database sqlite3
Mail Direct

```

**Comment by jochenkirstaetter** [comment] 2017-11-06 07:54
Duplicate of #294

**Comment by felixrieseberg** [comment] 2017-12-01 21:40
We now have 1.5 out, so I'm closing this.

**Closed by felixrieseberg** 2017-12-01 21:40 UTC
