### ISSUE TITLE
0.5.1 Not Loading Posts

### ISSUE THREAD

**Issue by flikteoh** [TryGhost/Ghost-Desktop#159] opened 2016-06-12 07:25 UTC
Not sure if it's a known issue.

After manually updated the App to 0.5.1, when clicking on a post for editing the post is not loading.

It just shows a blank screen.

![screenshot 2016-06-12 at 3 24 38 pm](https://cloud.githubusercontent.com/assets/1472065/15989716/cef39b00-30b1-11e6-92e0-328e7ccb7d7d.png)

2. Code Injection forms has this icon appeared on every empty line.

![screenshot 2016-06-12 at 3 23 33 pm](https://cloud.githubusercontent.com/assets/1472065/15989712/bc79ab40-30b1-11e6-85f3-1cb509258db3.png)

**Comment by felixrieseberg** [comment] 2016-06-13 05:37
Hey, that's fascinating, thanks for reporting. I have no idea what could be going on here, but I assume that the issue is somewhere with your actual blog. A few questions I have:

 * Which version of Ghost are you running?
 * If you open up the "Developer Tools (Current Blog)" and go to the "Console", do you see anything funky there? Everything might be interesting.
* What's your operating system?

**Comment by flikteoh** [comment] 2016-06-13 08:01
Hey @felixrieseberg 

I'm currently on Ghost 0.8.0 and Mac OSX 10.11.5

Here's what shows up in console.
![screen shot 2016-06-13 at 15 59 53](https://cloud.githubusercontent.com/assets/1472065/16000625/054a1930-3180-11e6-85ea-b6a9a8a0236c.png)

**Comment by ErisDS** [comment] 2016-06-13 11:01
Hey there @flikteoh thanks for reporting this and providing all the extra information. The bug with the editor not loading is a bug with Ghost. It lives [here](https://github.com/TryGhost/Ghost/issues/6914) and is being investigated at the moment - we just don't know what's causing it - it seems completely intermittent 😞 

The funny character in code injection is interesting. Do you also see similar characters in the post settings menu at all? I've seen that too and always thought it was a build problem, but perhaps the two things are symptoms of some underlying encoding-related issue.

I'm going to close this issue here because there's nothing the lovely @felixrieseberg and his excellent Ghost-Desktop team can do to solve this - it's all on Team Ghost 😉 . We're aiming to have it located & resolved by the next Ghost release.

**Closed by ErisDS** 2016-06-13 11:01 UTC

**Comment by flikteoh** [comment] 2016-06-13 12:00
Hi @ErisDS nope there's no funny character I see in post settings.

Thanks for the prompt respond. I hope it can be resolved soon. The desktop app is really useful but for now I just have to fallback to browser.

**Comment by ErisDS** [comment] 2016-06-13 13:19
@flikteoh if you don't mind could you answer a couple more questions to help us get to the bottom of this?

Are you self hosted or running Ghost on Ghost(Pro)?
When you say it works in the browser - which browser? As this is an issue with Ghost it should occur the same!

**Comment by flikteoh** [comment] 2016-06-14 02:42
Hey @ErisDS 

I'm self hosted on Digital Ocean. Ghost 0.8.0

When I'm on the Ghost Desktop App, editing screen shows blank for existing posts that I'm trying to edit.

While on Safari, editing seems to work just as it should.

I hope that helps.
